version: '3'
services:
  web:
    image: developius/swarm-app-node:0.0.2
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - dockercon
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - dockercon
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  dockercon:
    driver: overlay